"""Randomly pick customer and print customer info"""

from random import choice
from customers import get_customers_from_file
from sys import argv


def random_winner(customers):
	"""Call random winner using the list generated by customers program"""


	chosen_customer = choice(customers)

	print "Tell {} at {} that they've won".format(chosen_customer.name, 
		chosen_customer.email
		)

def run_raffle():
	"""Run the raffle"""

	customers = get_customers_from_file("customers.txt")
	random_winner(customers)

customer_file_path = argv[1:]

if __name__ == "__main__":
	run_raffle()


#   customer-name | email | street | city | zipcode

# Hint: remember to import any functions you need from
# other files or libraries
